steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - docker login --username=$$USERNAME --password=$$PASSWORD
    entrypoint: bash
    secretEnv:
      - USERNAME
      - PASSWORD
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - docker buildx create --use
    entrypoint: bash
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - >-
        docker buildx build
        -t gcr.io/${PROJECT_ID}/node-pkg
        --platform=linux/amd64 --push .
    entrypoint: bash
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - >-
        docker buildx build
        -t $$USERNAME/node-pkg
        --platform=linux/amd64,linux/arm64,linux/ppc64le --push .
    entrypoint: bash
    secretEnv:
      - USERNAME
options:
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
    - versionName: 'projects/${PROJECT_ID}/secrets/docker-password/versions/1'
      env: PASSWORD
    - versionName: 'projects/${PROJECT_ID}/secrets/docker-username/versions/1'
      env: USERNAME
